### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by TeetawatChitpitak** [dagatsoin/cordova-plugin-mapbox#3]
i am new with cordova ,now i use cordova with quasar mode  can you explain me how to install this plugin

**Comment by dagatsoin** [comment]
hi @TeetawatChitpitak, to install it you need to run `$ cordova plugin add https://github.com/dagatsoin/cordova-plugin-mapbox` 

You can also do `$ cordova plugin add https://github.com/dagatsoin/cordova-plugin-mapbox#7037d211013a7fc693690d86453cf78c032ca3ee` where the hash is a specific commit hash in case you need to pin your dependencies (which is recommended)
